"""Typed payload contracts for the Judgement AI Agent."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal


AccidentType = Literal["fall_from_height", "slip_and_fall", "fire_explosion", "other"]
EventLabel = Literal[
    "person",
    "no_helmet", "no_safety_vest", "no_mask",
    "no_gloves", "no_safety_shoes", "no_goggles",
    "red_zone_entry",
]


@dataclass
class VisualObservation:
    """Input from a future PT model, Qwen2.5-VL, or manual signal."""

    camera_id: str = "Camera 15"
    zone_id: str = "sidewalk_scaffold_red_zone"
    zone_name: str = "비계 하부 RED ZONE"
    detected_at: str = "2023-07-09T09:32:00"
    manual_description: str = ""
    image_url: str | None = None
    image_base64: str | None = None
    video_url: str | None = None
    video_base64: str | None = None
    video_path: str | None = None
    labels: list[str] = field(default_factory=list)
    confidence: float = 0.85
    bbox_xyxy: list[float] | None = None
    clip_path: str | None = "video/accident_video.mp4"
    clip_start_offset: float | None = 0.0
    clip_end_offset: float | None = 18.5


@dataclass
class AccidentJudgment:
    """Normalized accident type decision."""

    accident_type: AccidentType
    accident_type_ko: str
    agent_verdict: Literal["accident", "near_miss", "normal"]
    confidence: float
    summary: str
    details: str
    evidence: list[str]
    model: str
    raw: dict[str, Any] = field(default_factory=dict)


@dataclass
class EventLog:
    """Safety event log generated by the judgement agent."""

    event_type: Literal["PPE_VIOLATION", "RED_ZONE_ENTRY"]
    label: EventLabel
    message: str
    confidence: float
    severity: Literal["medium", "high"]


@dataclass
class AgentOutput:
    """Full agent output matching the DB seed video-part shape."""

    judgment: AccidentJudgment
    event_logs: list[EventLog]
    video_part_tables: dict[str, list[dict[str, Any]]]
    pt_status: dict[str, Any]


def now_iso() -> str:
    return datetime.now().replace(microsecond=0).isoformat()
